name: SonarCloud

on:
  push:
    branches:
      - main          # ↩️ ajusta si tu rama principal se llama distinto
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build & Analyze on SonarCloud
    runs-on: ubuntu-latest

    steps:
      # 1) Clonar repo con historial completo (necesario para PR decoration)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Configurar JDK (17 es el mínimo recomendado para Teammates)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # 3) (Opcional) Cache de dependencias Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      # 4) Compilar y ejecutar escaneo SonarCloud
      - name: Build & SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew build sonarqube \
            -Dsonar.projectKey=andre98652_TeamMatesSonarQube \
            -Dsonar.organization=andre98652 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN

